version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: 'ns-us-mongodb'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadm
      - MONGO_INITDB_ROOT_PASSWORD=mongoadm
      - MONGO_INITDB_DATABASE=notification_system
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  # user_service:notes_system
  #   restart: always
  #   image: notification_system.user_service:latest
  #   container_name: ns-user-service
  #   ports:
  #     - 10005:10005